name: Hello World!

on:
  push:
    branches:
      - master
      # note that your "main" branch might be called main instead of master

jobs:
  hello_world_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Say hello
        run: |
          echo "Hello World!"
      - name: Print Date
        run: |
          date
      - name: Print Folder
        run: |
          ls -la

  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Deploy code
        uses: appleboy/ssh-action@v0.1.2
        with:
            host: ${{secrets.SSH_HOST}}
            key: ${{secrets.SSH_KEY}}
            username: ${{secrets.SSH_NAME}}
            passphrase: ${{ secrets.SSH_PASS }}
            script: |
              mkdir test
              cd test
              git clone https://github.com/yanchengzeng/full-stack-open-pokedex.git
              echo "Nice Job"
      
      
      
